import React from "react";
import DividerWithText from "./DividerWithText";
import { Chrono } from "react-chrono";
import ChronoDetail from "./ChronoDetail";
import Image from "next/image";
import ArmyLogo from "../public/army-logo.svg?url";
import NasaLogo from "../public/nasa-logo.svg?url";
import UvaLogo from "../public/uva-logo.svg?url";

/***************************************************************************************
 *  REFERENCES
 *
 *  Title: react-chrono
 *  Author: Prabhu Murthy
 *  Date: 1/4/2023
 *  Code version: 1.20.0
 *  URL: https://github.com/prabhuignoto/react-chrono
 *  Software License: MIT License
 ***************************************************************************************/

const Experience = () => {
  const items = [
    {
      workplace: "Leidos",
      jobTitle: "Software Engineer Intern",
      image: (
        <Image
          src="/leidos.jpg"
          width={75}
          height={75}
          alt="Leidos Logo"
          className="object-fit"
          style={{ height: 75 }}
        />
      ),
      time: "May 2023 - Present",
    },
    {
      workplace: "University of Virginia",
      jobTitle: "Undergraduate Teaching Assistant",
      image: (
        <Image
          src={UvaLogo}
          width={75}
          height={75}
          alt="UVA Logo"
          className="object-fit"
          style={{ height: 75 }}
        />
      ),
      time: "Jan 2022 - Present",
      listItems: [
        `• Grade assignments, projects, and tests for CS 4750 (Database Systems).`,
        `• Attended lectures and hosted office hours three times a week, offering additional support to students by answering questions, reviewing course material, providing one-on-one assistance with assignments, and responding to discussion board posts.`,
        `• Delivered lecture to over 100 students during the professor's absence, effectively conveying complex database topics to ensure continuity in learning.`,
        `• Collaborated with the professor and other teaching assistants to develop instructional materials, including homework assignments and exams.`,
      ],
    },
    {
      workplace: "U.S. Army Technology Development Directorate",
      jobTitle: "Software Engineering Intern",
      image: (
        <Image
          src={ArmyLogo}
          width={75}
          height={75}
          alt="Army Logo"
          className="object-fit"
          style={{ height: 75 }}
        />
      ),
      time: "Aug 2022 - Mar 2023",
      listItems: [
        `• Facilitated preparations for a flight demonstration of multiple autonomous unmanned aircraft.`,
        `• Supported design and installation of computer networks used for data acquisition and flight control.`,
        `• Communicated autonomous flight software design solutions to audience of computer, aerospace, and mechanical engineers.`,
      ],
    },
    {
      workplace: "NASA Langley Research Center",
      jobTitle: "Research Mentee - Structural & Thermal Systems",
      image: (
        <Image
          src={NasaLogo}
          width={75}
          height={75}
          alt="Nasa Logo"
          style={{ height: 75 }}
        />
      ),
      time: "Aug 2019 - May 2020",
      listItems: [
        `• Enhanced a Python sizing optimization script for the CobraMRV Mars Lander Vehicle by adding a user-friendly GUI, a sensitivity graph generator that compares structural mass and load case parameters, and the ability to accept other CobraMRV model variants as input.`,
        `• Developed code to interface with engineering software including NASTRAN and HyperSizer.`,
        `• Authored APA research paper that documents the improvements made to the Python sizing optimization script as well as an analysis of the sensitivity graphs generated by the script.`,
        `• Presented findings to a research symposium and branch meeting with industry professionals.`,
      ],
    },
    {
      workplace: "Tabb Library",
      jobTitle: "Library Clerk Aide",
      image: (
        <Image
          src="/library-logo.jpg"
          width={75}
          height={75}
          alt="Library Logo"
          style={{ height: 75 }}
        />
      ),
      time: "Jun 2018 - Apr 2020",
      listItems: [
        `• Organized book carts and returned books to their designated locations, ensuring proper organization and adherence to the library's classification system.`,
        `• Assisted patrons in locating books, DVDs, and other materials, utilizing knowledge of the library's cataloging system.`,
      ],
    },
  ];

  return (
    <div className="max-w-[1240px] m-auto items-center p-3" id="experience">
      <DividerWithText text="Experience" />

      {/* Timeline - Web */}
      <div className="hidden min-[540px]:flex m-auto items-center justify-center w-100 h-100">
        <Chrono
          className="text-left"
          mode="VERTICAL"
          cardHeight="100"
          theme={{
            primary: "#212427",
            titleColor: "#212427",
            cardBgColor: "#FAF9F6",
          }}
          hideControls
          disableClickOnCircle
          activeItemIndex={-1}
        >
          {items &&
            items.map((item, index) => (
              <ChronoDetail
                key={index}
                image={item.image}
                workplace={item.workplace}
                jobTitle={item.jobTitle}
                time={item.time}
                listItems={item.listItems}
              />
            ))}
        </Chrono>
      </div>

      {/* Timeline - Mobile */}
      <div className="min-[540px]:hidden">
        {items &&
          items.map((item, index) => (
            <ChronoDetail
              key={index}
              image={item.image}
              workplace={item.workplace}
              jobTitle={item.jobTitle}
              time={item.time}
              listItems={item.listItems}
            />
          ))}
      </div>
    </div>
  );
};

export default Experience;
